name: Cppcheck

on:
  pull_request:
    paths:
      - CMakeLists.txt
      - .github/workflows/cppcheck.yml
      - src/**
  push:
    branches:
      - master
    paths:
      - CMakeLists.txt
      - .github/workflows/cppcheck.yml
      - src/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up cppcheck
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-name: cppcheck
          create-args: >-
            cppcheck=2.21.0

      - name: Run cppcheck
        shell: micromamba-shell {0}
        run: |
          cppcheck --version
          cmake -S . -B build/cppcheck -DAPOPLEXY_BUILD_APP=OFF
          cmake --build build/cppcheck --target cppcheck
