name: Cppcheck

on:
  pull_request:
    paths:
      - CMakeLists.txt
      - .github/workflows/cppcheck.yml
      - cmake/**
      - src/**
  push:
    branches:
      - main
    paths:
      - CMakeLists.txt
      - .github/workflows/cppcheck.yml
      - cmake/**
      - src/**
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - name: Check out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up cppcheck
        uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3
        with:
          environment-name: cppcheck
          create-args: >-
            cppcheck=2.21.0

      - name: Run cppcheck
        shell: micromamba-shell {0}
        run: |
          cppcheck --version
          cmake -S . -B build/cppcheck \
            -DAPOPLEXY_BUILD_APP=OFF \
            -DAPOPLEXY_BUILD_PR=OFF
          cmake --build build/cppcheck --target cppcheck
